IZ.Web/Models/ErrorViewModel.cs
using System;

namespace IZ.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IZ.Web/Controllers/DemIzvjestajiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IZ.BLL.Interfejsi;
using IZ.Model.VM;

namespace IZ.Web.Controllers
{
    public class DemIzvjestajiController : Controller
    {

        private IDemIzvjestaji _demIzvjestajiServis;
        private IIzvjestaji _izvjestajiServis;
        public DemIzvjestajiController(IDemIzvjestaji demIzvjestajiServis,   IIzvjestaji izvjestajiServis)
        {
            _demIzvjestajiServis = demIzvjestajiServis;
            _izvjestajiServis = izvjestajiServis;
        }

        //ovo ispod je bez veze defaultna metoda
        public IActionResult Index()
        {
            return View();
        }

        public string VratiDefinicijeIzvjestaj(int tipId)
        {
            var lista = _demIzvjestajiServis.VratiIzvjestajPoTipu(tipId);
            return lista;
        }
        

        public IActionResult TipIzvjestaja()
        {           
            ViewBag.SelektTip = _demIzvjestajiServis.VratiTipove();
            ViewBag.SelektDef = _demIzvjestajiServis.VratiDefinicije();
            return View("Index");
        }

        [HttpGet]
        public string VratiIzvjestajPoTipu(int tipId)
        {
            var izvjestaj = _izvjestajiServis.VratiIzvjestajePoTipu(tipId);
            return izvjestaj;
        }  
    }
}

IZ.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using IZ.Web.Models;

namespace IZ.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IZ.Web/Controllers/IzvjestajiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IZ.BLL.Interfejsi;
using IZ.Model.VM;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Xml;

namespace IZ.Web.Controllers
{
    public class IzvjestajiController : Controller
    {

        private IIzvjestaji _izvjestajiServis;
        public string _rootPath;
        public IzvjestajiController(IIzvjestaji izvjestajiServis, IWebHostEnvironment env) // IWebHostEnvironment
        {
            _izvjestajiServis = izvjestajiServis;
            _rootPath = env.WebRootPath;
        }

        public IActionResult GenerisaniIzvjestaji()
        {
            ViewBag.SelektTip = _izvjestajiServis.VratiTipoveIzvjestaja();
            var lista = _izvjestajiServis.VratiGenIzvjestaje();
            return View(lista);
        }

        public string VratiIzvjestaje(string datumOd, string datumDo, string definicijaId)
        {
            var lista = _izvjestajiServis.VratiIzvjestajePo3Parametra(datumOd, datumDo, definicijaId);
            return lista;
        }
        public IActionResult UcitajDodajSemu()
        {
            return View("DodajSemu");
        }

        public IActionResult UcitajDodajIzvjestaj()
        {
            ViewBag.SelektTip = _izvjestajiServis.VratiTipoveIzvjestaja();
            return View("DodajIzvjestaj");
        }

        public string VratiSemu(int semaId)
        {
            return _izvjestajiServis.VratiSemu(semaId);
        }

        public bool SpasiSemu(string semaNaziv, string sema)
        {
            return true;
        }
        public bool SpasiPodatke(int semaId, string datumOd, string datumDo, string datumPodnosenja, string podaci, string podaciBezPrveDvijeKolone, string jsonSamo, string jsonPoseban, string jsonPodaciBezHeadera, string nazivFajla)
        {
            _izvjestajiServis.GenerisiIzvjestaj(semaId, datumOd, datumDo, datumPodnosenja, jsonPodaciBezHeadera, nazivFajla);
            return true;
        }

        [HttpPost]
        public async Task<ActionResult> UploadFile(IFormFile file)
        {
            if (file.Length > 0)
            {
                var filePath = Path.Combine(_rootPath + "\\UploadExcel\\", file.FileName); // spasava u wwwroot
                // var filePath = Path.Combine("D:\\novi\\", file.FileName); moze spasit i na drugi disk
                using (var stream = System.IO.File.Create(filePath))
                {
                    await file.CopyToAsync(stream);
                }
            }
            return null;
        }

        public bool SemaPostoji(string semaNaziv, string sema)
        {
            //ako u bazi postoji sema sa tim Naziv poljem vrati true
            //ako postoji sadrzaj kolone Shema u bazi u tabeli Seme da je isti kao i proslijedjeni string sema vrati true
            // info: poredis ih kao stringove
            //ako nema nista od tog vrati false
            return false;
        }

        public IActionResult DownloadXML(int Id, string xmlIme)
        {
            var podaci = _izvjestajiServis.VratiXML(Id);
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(podaci.text2);
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            using (XmlWriter writer = XmlWriter.Create(_rootPath + "\\TempXML\\" + podaci.text1 + ".xml", settings))
            {
                doc.Save(writer);
            }
            var filePath = Path.Combine(_rootPath + "\\TempXML\\", podaci.text1 + ".xml");
            string fileName = podaci.text1 + ".xml";
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
                return File(fileBytes, "application/force-download", fileName);
            }
            return Ok("Došlo je do greške!Fajl sa ovim nazivom ne postoji.");
        }

        public IActionResult DownloadExcel(string xmlNaziv)
        {
            var filePath = Path.Combine(_rootPath + "\\UploadExcel\\", xmlNaziv);
            // string fileName = xmlNaziv + ".xls";          
            if (System.IO.File.Exists(filePath))
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
                return File(fileBytes, "application/force-download", xmlNaziv);
            }
            //else
            //{
            //    var filePath1 = Path.Combine(_rootPath + "\\UploadExcel\\", xmlNaziv + ".xlsx");
            //    string fileName1 = xmlNaziv + ".xlsx";
            //    if (System.IO.File.Exists(filePath1))
            //    {
            //        byte[] fileBytes = System.IO.File.ReadAllBytes(filePath1);
            //        return File(fileBytes, "application/force-download", fileName1);
            //    }
            //}
            return Ok("Došlo je do greške!Fajl sa ovim nazivom ne postoji.");
        }

        public IActionResult Obrisi(int Id)
        {
            _izvjestajiServis.Obrisi(Id);
            var lista = _izvjestajiServis.VratiGenIzvjestaje();
            return View("GenerisaniIzvjestaji", lista);
        }

        [HttpGet]
        public string VratiIzvjestajePoTipu(int tipId)
        {
            var izvjestaji = _izvjestajiServis.VratiIzvjestajePoTipu(tipId);
            return izvjestaji;
        }
    }
}

IZ.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Izvjestaji";
}

    <div class="text-center">
        <p class="display-4">Odaberi model izvještaja:</p>

        

        <input type="file" id="fileUpload" accept=".xls,.xlsx" /><br />
        <button type="button" id="uploadExcel">Convert</button>
        <pre id="jsonData"></pre>
    </div>

IZ.Web/Views/Izvjestaji/DodajSemu.cshtml
@{
    ViewData["Title"] = "DodajSemu";
}
<style>
    div {
        margin-bottom: 5px;
    }

    textarea {
        min-height: 250px;
    }
</style>
<form method="post" asp-action="SpasiSemu" asp-controller="Izvjestaji">
</form>
<input type="file" id="fileUpload" accept=".xls,.xlsx" class="form-control-file" value="Odaberite fajl" />
<br />
<div id="kontejner-svega" style="display:none">
    <div class="row">
        <label class="col-3">Naziv šeme:</label>
        <input id="naziv-seme" class="col-lg-3 col-md-4 col-sm form-control">
    </div>
    <div id="nekiHTML" class="row" style="font-weight:600">

    </div>
    <hr />
    <div class="row">
        <label class="col-3">
            Šema:
        </label>
        <textarea id="json-seme" class="col form-control" readonly></textarea>
    </div>
    @*<div class="row">
            <label class="col-3">Dokument: </label>
            <textarea  id="dokument-seme" class="col form-control"></textarea>
        </div>
        <div class="row">
            <label class="col-3">Obrazac 1:</label>
            <textarea  id="obrazac-seme" class="col form-control"></textarea>
        </div>*@
</div>
<hr>
<button id="spasi-semu" type="button" class="row btn btn-danger" disabled>Spasi šemu</button>
<br />
<br />

<div id="model-postoji" class="row alert alert-danger alert-dismissible" style="display:none">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    Šema sa tim nazivom/modelom već postoji.
</div>

<script>
    document.getElementById("fileUpload").addEventListener("change", function (event) {
        selectedFile = event.target.files[0];

        $("#loading-img").css("display", "block");
        if (selectedFile) {
            var fileReader = new FileReader();
            fileReader.onload = function (event) {
                var data = event.target.result;

                var workbook = XLSX.read(data, {
                    type: "binary"
                });

                var heder = Glavna.VratiHeader(workbook);

                $("#json-seme").val(JSON.stringify(heder, null, 4));
                //definisanje same seme preko header-a KRAJ

                rowObject = XLSX.utils.sheet_to_row_object_array(workbook.Sheets[workbook.SheetNames[0]], { raw: false });

                $("#dokument-seme").val(JSON.stringify(XLSX.utils.sheet_to_row_object_array(workbook.Sheets[workbook.SheetNames[2]], { raw: false }), null, 4));

                $("#obrazac-seme").val(JSON.stringify(XLSX.utils.sheet_to_row_object_array(workbook.Sheets[workbook.SheetNames[3]], { raw: false }), null, 4));

                var naziv = $("#fileUpload").val();
                naziv = naziv.split("\\");
                naziv = naziv[naziv.length - 1];
                naziv = naziv.split(".");
                naziv = naziv[naziv.length - 2];
                $("#naziv-seme").val(naziv);

                $("#kontejner-svega").css("display", "block");
                $("#spasi-semu").prop("disabled", false);
                $("#loading-img").css("display", "none");
            };
            fileReader.readAsBinaryString(selectedFile);
        }
    });

    //provjeri validnost json-a
    $("#spasi-semu").on("click", function () {
        var uspjeh = true;

        $("textarea").each(function () {
            try {
                JSON.parse($(this).val());
                $(this).removeClass("border-danger");
                $(this).addClass("border-success");
            }
            catch{
                $(this).removeClass("border-success");
                $(this).addClass("border-danger");
                uspjeh = false;
            }
        });

        //ako je json validan
        if (uspjeh) {
            //provjeri postoji li takav model vec
            //posalji vrijednost modela i naziv modela
            modelPostoji = $.ajax({
                type: "GET",
                url: "/Izvjestaji/SemaPostoji/",
                data: "semaNaziv=" + $("#naziv-seme").val().trim() + "&sema=" + JSON.stringify(JSON.parse($("#json-seme").val()), null, 0),
                async: false,
                success: function (sema) {

                }

            });
            if (modelPostoji.responseJSON == "true" || modelPostoji.responseJSON == "True" || modelPostoji.responseJSON == "1") {
                $("div#model-postoji").prop("display", true);
                return;
            } else {
                $("div#model-postoji").prop("display", false);

                spasiSemu = $.ajax({
                    type: "POST",
                    url: "/Izvjestaji/SpasiSemu/",
                    data: "semaNaziv=" + $("#naziv-seme").val().trim() + "&sema=" + JSON.stringify(JSON.parse($("#json-seme").val()), null, 0), /*+ "&dokument=" + JSON.stringify(JSON.parse($("#dokument-seme").val()), null, 0) + "&obrazac=" + JSON.stringify(JSON.parse($("#obrazac-seme").val()), null, 0),*/
                    async: false,
                    success: function (uspjesnoSpaseno) {

                    }

                });
            }
        }
        else {
            return false;
        }
    });
</script>

IZ.Web/Views/Izvjestaji/GenerisaniIzvjestaji.cshtml
@model IZ.Model.VM.ListaSveVM
@{
    ViewData["Title"] = "GenerisaniIzvjestaji";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script type="text/javascript">
    $(document).ready(function () {

        $('#tabela').dataTable({
            //"scrollX": true,
            //select: {
            //style: 'single'
            //},
            //dom: 'Blfrtip',

            language: {
                buttons: {
                    copyTitle: 'Uspjeh',
                    copySuccess: {
                        _: '%d redova kopirano',
                        1: '1 red kopiran'
                    }
                },
                processing: "Upit se obrađuje...",
                search: "Pretraga&nbsp;:",
                lengthMenu: "_MENU_ redova",
                info: "Prikazano _START_  do _END_ od ukupno _TOTAL_ redova",
                infoEmpty: "Nema zapisa...",
                infoFiltered: "(filtrirano _MAX_ redova ukupno)",
                infoPostFix: "",
                loadingRecords: "Zapisi se učitavaju...",
                zeroRecords: "U tabeli je nula redova.",
                emptyTable: "Tabela je prazna!",
                select: {
                    rows: {
                        _: "",
                        0: "",
                        1: ""
                    }
                },
                paginate: {
                    first: "Prvi",
                    previous: "<i class='fas fa-arrow-left'></i>",
                    next: "<i class='fas fa-arrow-right'></i>",
                    last: "Posljednji"
                },
                aria: {
                    sortAscending: ": ",
                    sortDescending: ": "
                }
            },
            order: [[0, 'dsc']],
            ajax: {
                "type": "POST",
                "url": "/Izvjestaji/VratiIzvjestaje",
                "data": function (d) {
                    d.datumOd = $("#datum-od").val();
                    d.datumDo = $("#datum-do").val();
                    d.definicijaId = $("#selekt-izv").val();
                },
                "dataSrc": ""
            },
            columns: [
                {
                    data: "IzvjestajiGenerisaniId",
                    "width": 20,
                    "className": 'dt-body-center'
                },
                {
                    data: "DatumKreiranja",
                    "mRender": function (data, type, full) {
                        return (moment(data).format("DD-MM-YYYY"));
                    }
                },
                { data: "NazivXmlfajla" },
                { data: "KratkiNazivDefinicijeI" },
                {
                    data: null,
                    "orderable": false,
                    "searchable": false,
                    "className": 'dt-body-center',
                    "defaultContent": '<span class="d-flex justify-content-around"><a href="#" data-toggle="tooltip" data-placement="top" title="Generiši XML" class="down"><i style="color:#F8A000;" class="material-icons md-fix">generiši</i></a><a href="#" style="display:none" style="color:red" class="arhiviraj"><i class="material-icons md-fix">clear</i></a></span>'
                },
                {
                    data: null,
                    "orderable": false,
                    "searchable": false,
                    "className": 'dt-body-center',
                    "defaultContent": '<span class="d-flex justify-content-around"><a href="#" data-toggle="tooltip" data-placement="top" title="Downloaduj excel" class="downexc"><i style="color:#F8A000;" class="material-icons md-fix">download</i></a><a href="#" style="display:none" style="color:red" class="arhiviraj"><i class="material-icons md-fix">clear</i></a></span>'
                },
                {
                    data: null,
                    "orderable": false,
                    "searchable": false,
                    "className": 'dt-body-center',
                    "defaultContent": '<span class="d-flex justify-content-around"><a href="#" data-toggle="tooltip" data-placement="top" title="Obriši izvještaj" class="obrisi"><i style="color:#F8A000;" class="material-icons md-fix">obriši</i></a><a href="#" style="display:none" style="color:red" class="arhiviraj"><i class="material-icons md-fix">clear</i></a></span>'
                }
            ]
        });   //kraj tabele

        var table = $('#tabela').DataTable();

        // Primjeni pretragu samo za odabrane kolone
        table.columns([1, 2, 3, 4]).every(function () {
            var that = this;

            $('input', this.footer()).on('keyup change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });

        $('#tabela tbody').on('click', 'a.down', function () {
            var ppId = table.row($(this).parents('tr')).data().IzvjestajiGenerisaniId;
            var xmlIme = table.row($(this).parents('tr')).data().NazivXmlfajla;
            $("#downloadd").val(ppId);
            $("#xmlIme").val(xmlIme);
            $('#downloadd').click();
        });

        $('#tabela tbody').on('click', 'a.downexc', function () {
            var xmlNaziv = table.row($(this).parents('tr')).data().ImportedExcel;
            $("#excel").val(xmlNaziv);
            $('#excel').click();
        });

        $('#tabela tbody').on('click', 'a.obrisi', function () {
            var ppId = table.row($(this).parents('tr')).data().IzvjestajiGenerisaniId;
            $("#obrisi").val(ppId);
            $('#obrisi').click();
        });

        //$(".paginate_button").css("background-image", "none");
        //$(".paginate_button").css("background-color", "white !important");
        //$(".paginate_button").css("border", "1px solid grey");
        //$(".paginate_button").css("border-radius", "50%");

    });//kraj ready
</script>


<!-- Pomocna polja -->
<form method="GET" asp-action="DownloadXML" asp-controller="Izvjestaji">
    <input id="downloadd" type="submit" name="Id" hidden />
    <input hidden id="xmlIme" name="xmlIme" value="" />
</form>

<form method="GET" asp-action="DownloadExcel" asp-controller="Izvjestaji">
    <input id="excel" type="submit" name="xmlNaziv" hidden />
</form>

<form method="GET" asp-action="Obrisi" asp-controller="Izvjestaji">
    <input id="obrisi" type="submit" name="Id" hidden />
</form>

<form>
    <div class="p-5 border rounded">
        <div class="form-group row">
            <div class="col-md-3">
                <label for="datum-od" class="col-form-label">Datum od:<span class="obavezno-polje"></span></label>
            </div>
            <div class="col">
                <div class="col-4">
                    <input id="datum-od" class="form-control" required />
                    <script>
                        $('#datum-od').datepicker({
                            uiLibrary: 'bootstrap4',
                            format: 'yyyy-mm-dd'
                        }).on('changeDate', function (ev) {
                            $("select").trigger("click");
                        });
                    </script>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3">
                <label for="datum-do" class="col-form-label">Datum do:<span class="obavezno-polje"></span></label>
            </div>
            <div class="col">
                <div class="col-4">
                    <input id="datum-do" class="form-control" required />
                    <script>
                        $('#datum-do').datepicker({
                            uiLibrary: 'bootstrap4',
                            format: 'yyyy-mm-dd'
                        }).on('changeDate', function (ev) {
                            $("select").trigger("click");
                        });
                    </script>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label for="selekt-tip" class="col-form-label">Tip izvještaja:<span class="obavezno-polje"></span></label>
            </div>
            <div class="col">
                <div class="col-4">
                    <select asp-items="@(new SelectList(ViewBag.SelektTip,"text1","text2"))" id="selekt-tip" class="form-control">
                        <option value="0">Odaberite</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label for="selekt-izv" class="col-form-label">Izvještaj:<span class="obavezno-polje"></span></label>
            </div>
            <div class="col">
                <div class="col-4">
                    <select id="selekt-izv" class="form-control">
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-6">
                <button id="prikazi" type="button" class="row btn btn-success" style="float: right; margin-top:5px; margin-right:1px">Prikaži izvještaje</button>
            </div>
        </div>
    </div>
</form><br />
<div class="col-12">
    <div style="width:100%">
        @*<a onclick="saljiInfo()"><div class="btn btn-success btn-sm" style="position:absolute; z-index:1;"><i class="material-icons">add</i></div></a>*@
        <table id="tabela" class="table table-hover full-width">
            <thead>
                <!-- atributi tabele -->
                <tr>
                    <th>#</th>
                    <th>Datum kreiranja</th>
                    <th>Naziv XML fajla</th>
                    <th>Kratki naziv definicije</th>
                    <th class="akcije">Generiši XML</th>
                    <th class="akcije">Download Excel</th>
                    <th class="akcije">Obriši</th>
                </tr>
            </thead>
            <tfoot>
                <!-- pretraga futer -->
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    @*<th>Datum kreiranja</th>
                        <th>Naziv XML fajla</th>
                        <th>Kratki naziv definicije</th>*@
                    <th></th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            var items = "<option value='0'>Odaberite</option>";
            $("#selekt-izv").html(items);
        });

        $("#selekt-tip").change(function () {
            var tipId = $("#selekt-tip").val();
            var url = "/Izvjestaji/VratiIzvjestajePoTipu";

            $.getJSON(url, { tipId: tipId }, function (data) {
                var item = "";
                item = '<option value="0">Odaberite</option>'
                $("#selekt-izv").empty();
                if (data != undefined) {
                    for (i = 0; i < data.length; i++) {
                        item += '<option value="' + data[i].text1 + '">' + data[i].text2 + '</option>'
                    }
                }
                else {
                    item = '<option value="0">Nema izvještaja</option>'
                }
                $("#selekt-izv").html(item);
            });
        });

        $("#prikazi").click(function () {
            var table = $('#tabela').DataTable();
            table.ajax.reload();
            // var definicijaId = $("#selekt-izv").val();
            // var datumOd =$("#datum-od").val();
            // var datumDo =  $("#datum-do").val();
            //var url = "/Izvjestaji/VratiIzvjestaje";

            //$.getJSON(url, {datumOd: datumOd, datumDo : datumDo, definicijaId: definicijaId}, function (data) {
            //    var item = "";

            //    if (data != undefined) {
            //        console.log(data)
            //        table.ajax(data);
            //    }
            //    else {
            //        item = '<option value="0">Nema izvještaja</option>'
            //    }
            //    $("#selekt-izv").html(item);
            //});
        });
    </script>
}

IZ.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IZ.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.15.3/xlsx.full.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.bs.min.js"></script>
    <script src="https://momentjs.com/downloads/moment.js" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Izvjestaji" asp-action="GenerisaniIzvjestaji">Generisani izvještaji</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Izvjestaji" asp-action="UcitajDodajIzvjestaj">Generiši izvještaj</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Izvjestaji" asp-action="UcitajDodajSemu">Dodaj model hedera</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DemIzvjestaji" asp-action="TipIzvjestaja">Tipovi Izvjestaja</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <img src="~/loading.gif" alt="loading" id="loading-img" class="centar-ekrana" />
            @RenderBody()
        </main>
    </div>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>